package kr.co.koscom.mydataservicewebdemo.model;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@ApiModel
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class AU11Request {
	
	@NotNull
	@ApiModelProperty(value = "트랜잭션 ID", example = "MD_SVC9999999_C1AAGU0000_ZWAACP0000_ZXAACP0000_20210701204521_000000000001")
	private String txId;
	
	@NotNull
	@ApiModelProperty(value = "기관코드", example = "C1AAGU0000")
	private String orgCode;
	
	@NotNull
	@ApiModelProperty(value = "권한부여 방식", example = "password")
	private String grantType;
	
	@NotNull
	@ApiModelProperty(value = "클라이언트 ID", example = "KSCCLI-SVC9999999-KyBW70m0ZM")
	private String clientId;
	
	@NotNull
	@ApiModelProperty(value = "클라이언트 Secret", example = "QW49A5sErtI659vjgdwyJvtEpR10d3LEG2xvtmSl")
	private String clientSecret;
	
	@NotNull
	@ApiModelProperty(value = "통합인증기관코드", example = "ZXAACP0000")
	private String caCode;
	
	@NotNull
	@ApiModelProperty(value = "전자서명 유형", example = "0")
	private String consentType;
	
	@ApiModelProperty(value = "consent 항목 길이", example = "0")
	private String consentLen;
	
	@ApiModelProperty(value = "전송요구내역", example = "")
	private String consent;
	
	@NotNull
	@ApiModelProperty(value = "고객 CI 정보", example = "lDu66vPB2OcbHhUYntiQ6aZtZlJEgDn4iDYQ3ZEvtLB3nBi8pT9CdWNqPfH//yYSZImzO1ooIj5WS1HNHQVP/w==")
	private String username;
	
	@NotNull
	@ApiModelProperty(value = "password 항목 길이", example = "3116")
	private String passwordLen;
	
	@NotNull
	@ApiModelProperty(value = "전송요구내역 전자서명 (signedConsent)", example = "MIAGCSqGSIb3DQEHAqCCCQ4wggkKAgEBMQ8wDQYJYIZIAWUDBAIBBQAwggFWBgkqhkiG9w0BBwGgggFHBIIBQ3siY29uc2VudE5vbmNlIjoiUXpBeE1qTTBOVFkzT0RsQiIsImNvbnNlbnQiOnsiZW5kX2RhdGUiOiIyMDIyMDgwNDE1MzAzMCIsInNuZF9vcmdfY29kZSI6IkMxQUFHVTAwMDAiLCJyY3Zfb3JnX2NvZGUiOiJNT1VFMDAwMTAyIiwicHVycG9zZSI6Iu2Gte2VqeyhsO2ajCIsInRhcmdldF9pbmZvIjpbeyJzY29wZSI6ImludmVzdC5saXN0In0seyJzY29wZSI6ImludmVzdC5hY2NvdW50In1dLCJob2xkaW5nX3BlcmlvZCI6IjIwMjQwODA0MTUzMDMwIiwiaXNfc2NoZWR1bGVkIjp0cnVlLCJjeWNsZSI6eyJhZGRfY3ljbGUiOiIxL0QiLCJmbmRfY3ljbGUiOiIxL1cifX19oIIFojCCBZ4wggSGoAMCAQICAwhc-zANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwJLUjESMBAGA1UECgwJU2lnbktvcmVhMRUwEwYDVQQLDAxBY2NyZWRpdGVkQ0ExGzAZBgNVBAMMElNpZ25Lb3JlYSBUZXN0IENBNTAeFw0yMTA2MDIwNjE0MDBaFw0yMjA2MDIxNDU5NTlaMIGEMQswCQYDVQQGEwJLUjESMBAGA1UECgwJU2lnbktvcmVhMRgwFgYDVQQLDA_thYzsiqTtirjsl4XsooUxGDAWBgNVBAsMD-2FjOyKpO2KuO2ajOyCrDEYMBYGA1UECwwP7YWM7Iqk7Yq47KeA7KCQMRMwEQYDVQQDDArqsJzsnbh0XzE1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxOuVlSfSV-1vSan6kdDmGaSFzfolct2sBS7u9eqXYurmhVh5EOnmoryU2CKHO28oLQgmD4cgycCsDZHITI5MW-zOLZcK1o4H9rWMs_qZTGAXwGzeXxxKEewtkdoZRdsTWJ_waGYrhDtLsccZKZorc0IVmGUCmPOGXl2WBQy_jIuTXB0hc7hAbo8nsMD6G-tRpB0NoO9VizMJ1j9A7dyJ1rppVQFQgFRgPC5kGGcZQ0SFujgx10NczTAl6mbSwKqM6RmksERk2Ghe9CM6A6BvloKFn_2XuHM_w17XcU82cJV74DdyA14F5gQ0K8NgWjsvDAxxuQuYpIKQSPflpdSJcQIDAQABo4ICRTCCAkEwgZMGA1UdIwSBizCBiIAU8XCpr2_PnYusgYXMFvR82YVcDMShbaRrMGkxCzAJBgNVBAYTAktSMQ0wCwYDVQQKDARLSVNBMS4wLAYDVQQLDCVLb3JlYSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBDZW50cmFsMRswGQYDVQQDDBJLaXNhIFRlc3QgUm9vdENBIDeCAQUwHQYDVR0OBBYEFF4JTWAXiVdmTA99YT3NVAVph8qjMA4GA1UdDwEB_wQEAwIGwDB7BgNVHSABAf8EcTBvMG0GCiqDGoyaRAUBAQUwXzAtBggrBgEFBQcCARYhaHR0cDovL3d3dy5zaWdua29yZWEuY29tL2Nwcy5odG1sMC4GCCsGAQUFBwICMCIeIMd0ACDHeMmdwRwAIMLc1djGqQAgx3jJncEcx4WyyLLkMGkGA1UdEQRiMGCgXgYJKoMajJpECgEBoFEwTwwK6rCc7J24dF8xNTBBMD8GCiqDGoyaRAoBAQEwMTALBglghkgBZQMEAgGgIgQg7u6TU9qUGIetP1y1po_6igk-sbyikIP60drJFqoq3RAwVgYDVR0fBE8wTTBLoEmgR4ZFbGRhcDovLzIxMS4xNzUuODEuMTAyOjY4OS9vdT1kcDExcDEzLG91PUFjY3JlZGl0ZWRDQSxvPVNpZ25Lb3JlYSxjPUtSMDoGCCsGAQUFBwEBBC4wLDAqBggrBgEFBQcwAYYeaHR0cDovLzIxMS4xNzUuODEuMTAxL29jc3AucGhwMA0GCSqGSIb3DQEBCwUAA4IBAQALIXpwBHrbeJnFMcfl7G3woodJRzSjvpNR_TrcCx1opVvxmgwVn7FbqWDf4eaX_ElLdnf6PpE0CbNGT4H4enRiW20XH7Id8PoZIxpRqBZwTrrNGWZt7J7cwSFFqucOM5-CHRlMG6Xgu45BUrHa0ok9-h0mEw7pQhn50I09hV_Zo0fJuDu1d53wtNslLi1FIuF1sFo6C2q1e87HVlSHb_8P46xpxeRGVHpVriZOdHOJCRTXlAvyW35PM7ah9ab7lAvkTYAa5TgmWJiuGb1HSlb1q8Tr29rZTDIJfgFBxLn7Xzk4VIwcW9ix6DvQ__Z5wCD5SMC1d2wYa6SlDvWq4NlcMYIB8jCCAe4CAQEwXDBVMRswGQYDVQQDDBJTaWduS29yZWEgVGVzdCBDQTUxFTATBgNVBAsMDEFjY3JlZGl0ZWRDQTESMBAGA1UECgwJU2lnbktvcmVhMQswCQYDVQQGEwJLUgIDCFz7MA0GCWCGSAFlAwQCAQUAoGkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjEwNzAxMTI1OTU0WjAvBgkqhkiG9w0BCQQxIgQgR0w8MeW52-usGNBCepTVun29J6DolI0Z5QZOIZMAVyEwDQYJKoZIhvcNAQEBBQAEggEAOku3WDygfLD3eaf56vlSqxqeoNA_sFeOhsZOAPLQJt7_5GweO36Lsdqy5hv-5XXr2Jlsupy3_fuhEq0pIZqg0fT8DYTayOGnZqqVASj7zq-ICZrbV5hshVO-_Hth4CH5ioiJryfmSc3sQSu8rKk09tx6aTGdVH30Yj1nqgljrJvWqJVRGQmSuTztBczSxdnMQs8qI2m2oCWpm9BKzg9mB9XtDpB-r8xkfD6QMFwtmhptnugCm1jp_POKY9kJZ2RzObd28GmMTmD3yb50iEw5H37273cgz3w_wt3ctwKgnviQhz7w1bOIcoQwjukXRgLa_44zm-zoLExO2vtYC_cDYQAA")
	private String password;
	
	@NotNull
	@ApiModelProperty(value = "본인확인 이용 여부", example = "0")
	private String authType;
	
	@ApiModelProperty(value = "본인확인 이용동의 전자서명 항목 길이 (signedPersonInfoReq의 길이)", example = "2936")
	private String signedPersonInfoReqLen;
	
	@ApiModelProperty(value = "본인확인 이용동의 전자서명 (signedPersonInfoReq)", example = "MIAGCSqGSIb3DQEHAqCCCIcwggiDAgEBMQ8wDQYJYIZIAWUDBAIBBQAwgdAGCSqGSIb3DQEHAaCBwgSBvzCAAgECBBBRekF4TWpNME5UWTNPRGxCMIAMUOuzuOyduO2ZleyduCDsnbTsmqnslb3qtIA667O47J247ZmV7J24IOyalOyyreyXkCDrj5nsnZjtlanri4jri6Qu7Lm07Lm07Jik7Y6Y7J20AwID-AAAMIAMIlNpZ25Lb3JlYSBVQ1BJRCBUb29sa2l0IGZvciBtb2JpbGUMBktPU0NPTTCAAgECAgEBAAAAAAwQd3d3Lm15ZGF0YS5jby5rcgAAoIIFojCCBZ4wggSGoAMCAQICAwhc-zANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwJLUjESMBAGA1UECgwJU2lnbktvcmVhMRUwEwYDVQQLDAxBY2NyZWRpdGVkQ0ExGzAZBgNVBAMMElNpZ25Lb3JlYSBUZXN0IENBNTAeFw0yMTA2MDIwNjE0MDBaFw0yMjA2MDIxNDU5NTlaMIGEMQswCQYDVQQGEwJLUjESMBAGA1UECgwJU2lnbktvcmVhMRgwFgYDVQQLDA_thYzsiqTtirjsl4XsooUxGDAWBgNVBAsMD-2FjOyKpO2KuO2ajOyCrDEYMBYGA1UECwwP7YWM7Iqk7Yq47KeA7KCQMRMwEQYDVQQDDArqsJzsnbh0XzE1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxOuVlSfSV-1vSan6kdDmGaSFzfolct2sBS7u9eqXYurmhVh5EOnmoryU2CKHO28oLQgmD4cgycCsDZHITI5MW-zOLZcK1o4H9rWMs_qZTGAXwGzeXxxKEewtkdoZRdsTWJ_waGYrhDtLsccZKZorc0IVmGUCmPOGXl2WBQy_jIuTXB0hc7hAbo8nsMD6G-tRpB0NoO9VizMJ1j9A7dyJ1rppVQFQgFRgPC5kGGcZQ0SFujgx10NczTAl6mbSwKqM6RmksERk2Ghe9CM6A6BvloKFn_2XuHM_w17XcU82cJV74DdyA14F5gQ0K8NgWjsvDAxxuQuYpIKQSPflpdSJcQIDAQABo4ICRTCCAkEwgZMGA1UdIwSBizCBiIAU8XCpr2_PnYusgYXMFvR82YVcDMShbaRrMGkxCzAJBgNVBAYTAktSMQ0wCwYDVQQKDARLSVNBMS4wLAYDVQQLDCVLb3JlYSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBDZW50cmFsMRswGQYDVQQDDBJLaXNhIFRlc3QgUm9vdENBIDeCAQUwHQYDVR0OBBYEFF4JTWAXiVdmTA99YT3NVAVph8qjMA4GA1UdDwEB_wQEAwIGwDB7BgNVHSABAf8EcTBvMG0GCiqDGoyaRAUBAQUwXzAtBggrBgEFBQcCARYhaHR0cDovL3d3dy5zaWdua29yZWEuY29tL2Nwcy5odG1sMC4GCCsGAQUFBwICMCIeIMd0ACDHeMmdwRwAIMLc1djGqQAgx3jJncEcx4WyyLLkMGkGA1UdEQRiMGCgXgYJKoMajJpECgEBoFEwTwwK6rCc7J24dF8xNTBBMD8GCiqDGoyaRAoBAQEwMTALBglghkgBZQMEAgGgIgQg7u6TU9qUGIetP1y1po_6igk-sbyikIP60drJFqoq3RAwVgYDVR0fBE8wTTBLoEmgR4ZFbGRhcDovLzIxMS4xNzUuODEuMTAyOjY4OS9vdT1kcDExcDEzLG91PUFjY3JlZGl0ZWRDQSxvPVNpZ25Lb3JlYSxjPUtSMDoGCCsGAQUFBwEBBC4wLDAqBggrBgEFBQcwAYYeaHR0cDovLzIxMS4xNzUuODEuMTAxL29jc3AucGhwMA0GCSqGSIb3DQEBCwUAA4IBAQALIXpwBHrbeJnFMcfl7G3woodJRzSjvpNR_TrcCx1opVvxmgwVn7FbqWDf4eaX_ElLdnf6PpE0CbNGT4H4enRiW20XH7Id8PoZIxpRqBZwTrrNGWZt7J7cwSFFqucOM5-CHRlMG6Xgu45BUrHa0ok9-h0mEw7pQhn50I09hV_Zo0fJuDu1d53wtNslLi1FIuF1sFo6C2q1e87HVlSHb_8P46xpxeRGVHpVriZOdHOJCRTXlAvyW35PM7ah9ab7lAvkTYAa5TgmWJiuGb1HSlb1q8Tr29rZTDIJfgFBxLn7Xzk4VIwcW9ix6DvQ__Z5wCD5SMC1d2wYa6SlDvWq4NlcMYIB8jCCAe4CAQEwXDBVMRswGQYDVQQDDBJTaWduS29yZWEgVGVzdCBDQTUxFTATBgNVBAsMDEFjY3JlZGl0ZWRDQTESMBAGA1UECgwJU2lnbktvcmVhMQswCQYDVQQGEwJLUgIDCFz7MA0GCWCGSAFlAwQCAQUAoGkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjEwNzAxMTI1OTUzWjAvBgkqhkiG9w0BCQQxIgQgJOM1LJudobhl55T9w0cHz0nZe5qEJlRsNT_S4kHlM5kwDQYJKoZIhvcNAQEBBQAEggEAd-OmPmaQ_PbxUtxruTn08wijp9IKjOVlYW2_qmtwguxTt2tj46V604Gz0hVbYofSVnFz6du-QGHcRDnAsX4kwBkXe0nEGLmpUZ3Z4rxeZhT7nZGiCCMsLsbxplpfo4NxUDHWNbOlZOOSiWwS1CAVhZyXuuqPlniWmvlT84e8Cl3Im3EO3sa3A82H-VDA8TbMBAchNycjTLVHE7cbRtdwKVc_loDxmWWoMf-0sQguGXjfeYhy9XP9CVjQ6LF5mwlBefBqioelstnUwJJAV2zyZVJMW2IOXJ-2unEses3Au1jgbYUiR6w6y5pX-m0InivNGmQZ1RTenBa6Yx5-Jhq_DAAA")
	private String signedPersonInfoReq;
	
	@NotNull
	@ApiModelProperty(value = "재전송공격 방지정보 1 (consentNonce)", example = "QzAxMjM0NTY3ODlB")
	private String consentNonce;
	
	@ApiModelProperty(value = "재전송공격 방지정보 2 (ucpidNonce)", example = "QzAxMjM0NTY3ODlB")
	private String ucpidNonce;
	
	@ApiModelProperty(value = "인증사업자 트랜잭션 아이디", example = "")
	private String certTxId;
	
	@ApiModelProperty(value = "서비스번호", example = "MOC1234567202105200001")
	private String serviceId;
}
